# Generated by Django 3.2.21 on 2023-10-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_activity_activity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Course', 'Class'), ('Group Counseling', 'Group Counseling'), ('Yoga Session', 'Yoga Session')], default='Course', max_length=20),
        ),
        migrations.DeleteModel(
            name='ActivityType',
        ),
    ]
