# Generated by Django 3.2.21 on 2023-10-07 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_remove_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='locaton',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='current_participants',
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='classes.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('Class', 'Class'), ('Group Counseling', 'Group Counseling'), ('Yoga Session', 'Yoga Session')], default='Class', max_length=20),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
