# Generated by Django 3.2.21 on 2023-10-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20231007_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='has_journal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='needs_journal',
            field=models.BooleanField(default=False),
        ),
    ]
