# Generated by Django 3.2.21 on 2023-10-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20231014_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
